from GymnomeAssembly import Dataset01V1
from GymnomeAssembly import Dataset02V1
from GymnomeAssembly import Dataset03V1
from GymnomeAssembly import Dataset04V1
from GymnomeAssembly import Dataset05V1
from GymnomeAssembly import Dataset06V1
from GymnomeAssembly import Dataset07V1
from GymnomeAssembly import Dataset08V1
from GymnomeAssembly import Dataset09V1
from GymnomeAssembly import Dataset10V1
from GymnomeAssembly import Dataset11V1
from GymnomeAssembly import Dataset12V1
from GymnomeAssembly import Dataset13V1
from GymnomeAssembly import Dataset14V1
from GymnomeAssembly import Dataset15V1
from GymnomeAssembly import Dataset16V1
from GymnomeAssembly import Dataset17V1
from GymnomeAssembly import Dataset18V1
from GymnomeAssembly import Dataset19V1
from GymnomeAssembly import Dataset20V1
from GymnomeAssembly import Dataset21V1
from GymnomeAssembly import Dataset22V1
from GymnomeAssembly import Dataset23V1

from GymnomeAssembly import Dataset01V2
from GymnomeAssembly import Dataset02V2
from GymnomeAssembly import Dataset03V2
from GymnomeAssembly import Dataset04V2
from GymnomeAssembly import Dataset05V2
from GymnomeAssembly import Dataset06V2
from GymnomeAssembly import Dataset07V2
from GymnomeAssembly import Dataset08V2
from GymnomeAssembly import Dataset09V2
from GymnomeAssembly import Dataset10V2
from GymnomeAssembly import Dataset11V2
from GymnomeAssembly import Dataset12V2
from GymnomeAssembly import Dataset13V2
from GymnomeAssembly import Dataset14V2
from GymnomeAssembly import Dataset15V2
from GymnomeAssembly import Dataset16V2
from GymnomeAssembly import Dataset17V2
from GymnomeAssembly import Dataset18V2
from GymnomeAssembly import Dataset19V2
from GymnomeAssembly import Dataset20V2
from GymnomeAssembly import Dataset21V2
from GymnomeAssembly import Dataset22V2
from GymnomeAssembly import Dataset23V2



